fix: Update templates to enable nginx for Docker Desktop
che-incubator/chectl pull request #1882
Opened 2021-12-08 10:38 UTC by tolusha

Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
Update templates to enable nginx for Docker Desktop

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20901

### How to test this PR?

N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2021-12-08 13:53 UTC, mmorhun approved these changes

2021-12-08 17:05 UTC, AndrienkoAleksandr commented
@tolusha  I enabled kubernetes on Docker Desktop 4.3.0 (71786) mac os Monterey, set up more RAM and tested this pr. Installation process is working:

```bash
› Installer type is set to: 'operator'
› Current Kubernetes context: 'docker-desktop'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✔ ✈️  Docker Desktop preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if kubectl context is Docker Desktop: Found docker-desktop.
    ✔ Verify remote kubernetes status...done.
    ✔ Check Kubernetes version: Found v1.22.4.
    ✔ Verify if nginx ingress is installed
    ↓ Installing nginx ingress [skipped]
      → Ngninx ingress is already setup.
    ✔ Verify domain is set... auto-assigning domain to 192.168.0.186.nip.io....set to 192.168.0.186.nip.io.
  ✔ Following Eclipse Che logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che Server logs...done
    ✔ Start following PostgreSQL logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plug-in Registry logs...done
    ✔ Start following Devfile Registry logs...done
    ✔ Start following Eclipse Che Dashboard logs...done
    ✔ Start following namespace events...done
  ✔ Create Namespace eclipse-che...[Exists]
  ✔ 🏃‍  Running the Eclipse Che operator
    ✔ Create ServiceAccount che-operator in namespace eclipse-che...done.
    ✔ Read Roles and Bindings...done.
    ✔ Creating Roles and Bindings...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Create backup and restore CRDs...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace eclipse-che...done.
    ✔ Operator pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Prepare Eclipse Che cluster CR...Done.
    ✔ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace eclipse-che...done.
  ✔ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Keycloak pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Devfile Registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Plug-in Registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che Dashboard pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che Server pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che status check...done
  ✔ Retrieving Che self-signed CA certificate...OK
  ✔ Prepare post installation output...done
  ✔ Show important messages
    ✔ Eclipse Che 7.41.0-SNAPSHOT has been successfully deployed.
    ✔ Documentation             : https://www.eclipse.org/che/docs/
    ✔ -------------------------------------------------------------------------------
    ✔ Users Dashboard           : https://che-eclipse-che.192.168.0.186.nip.io
    ✔ Admin user login          : "admin:admin". NOTE: must change after first login.
    ✔ -------------------------------------------------------------------------------
    ✔ Plug-in Registry          : https://plugin-registry-eclipse-che.192.168.0.186.nip.io/v3/
    ✔ Devfile Registry          : https://devfile-registry-eclipse-che.192.168.0.186.nip.io/
    ✔ -------------------------------------------------------------------------------
    ✔ [ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: /var/folders/0r/5kq8sbvs327grtqxjndc2zn00000gn/T/cheCA.crt.
   Documentation how to add a CA certificate into a browser: https://www.eclipse.org/che/docs/che-7/end-user-guide/importing-certificates-to-browsers/
Command server:deploy has completed successfully in 04:49.
```

But, when I opened che url:

This site can’t be reached

Do I need some extra steps to enable ingress ?

2021-12-09 06:50 UTC, tolusha commented
```
↓ Installing nginx ingress [skipped]
      → Ngninx ingress is already setup.
    ✔ Verify domain is set... auto-assigning domain to 192.168.0.186.nip.io....set to 192.168.0.186.nip.io.
```
Ngninx has been already enabled.
The idea is to test this PR without enabled ngninx to check if chectl enable it correctly

2021-12-09 16:33 UTC, AndrienkoAleksandr commented
@tolusha I tested this pr under the Windows 10 and docker Desktop 4.3.0 with wsl2. Works fine. I installed Eclipse Che, created and started workspace.

2021-12-09 16:49 UTC, AndrienkoAleksandr approved these changes

2021-12-09 22:57 UTC, AndrienkoAleksandr requested changes
Sorry, controller-v1.1.0 definetly doesn't work on Mac. I found that version controller-v1.0.0 works fine on Mac, but I didn't tested it on the Windows yet.

2021-12-10 06:57 UTC, tolusha commented
Dowgraded to v1.0.0
Could you retest pls?

2021-12-10 15:05 UTC, AndrienkoAleksandr approved these changes
Ok, I finally got it. For testing I used "Reset Kubernetes cluster", but I didn't cound one thing: after reset k8s api I have to quite from Docker Desktop program and start it again. Only after this manipulation load balancer works like expected and I can repeat installation on the clean flow... Or like alternative I have to reinstally Docker Desktop completely.... So revert, please, version 1.1.0 - it works for Mac os Monterey and Docker Desktop  4.3.0 and for Windows 10 too, sorry for delay.

2021-12-10 15:19 UTC, merged

2021-12-15 19:05 UTC, kollachaitanyakrishna commented
@AndrienkoAleksandr: I tried to create after resetting in my local docker instance. it is failing. 
<img width="939" alt="Screenshot 2021-12-16 at 12 25 16 AM" src="https://user-images.githubusercontent.com/64516009/146247797-9f4cc599-2512-440e-aec1-f6c143778b69.png">
<img width="1067" alt="Screenshot 2021-12-16 at 12 29 06 AM" src="https://user-images.githubusercontent.com/64516009/146248308-a7df98e4-f1f8-4bf8-ba60-a3ff76b22613.png">

### **Below is the log** 

`-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    0.24.1
  Build:      git-ce418168f
  Repository: https://github.com/kubernetes/ingress-nginx
-------------------------------------------------------------------------------

W1215 18:58:17.719433       8 flags.go:214] SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)
nginx version: nginx/1.15.10
W1215 18:58:17.724016       8 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1215 18:58:17.724318       8 main.go:205] Creating API client for https://10.96.0.1:443
I1215 18:58:17.736127       8 main.go:249] Running in Kubernetes cluster version v1.22 (v1.22.4) - git (clean) commit b695d79d4f967c403a96986f1750a35eb75e75f1 - platform linux/amd64
I1215 18:58:18.154623       8 main.go:124] Created fake certificate with PemFileName: /etc/ingress-controller/ssl/default-fake-certificate.pem
W1215 18:58:18.162375       8 store.go:613] Unexpected error reading configuration configmap: configmaps "nginx-configuration" is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "ingress-nginx"
I1215 18:58:18.168094       8 nginx.go:265] Starting NGINX Ingress controller
E1215 18:58:18.186123       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:152: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "endpoints" in API group "" at the cluster scope
E1215 18:58:18.186124       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:155: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "configmaps" in API group "" at the cluster scope
E1215 18:58:18.186663       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:154: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
E1215 18:58:18.186840       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:153: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "services" in API group "" at the cluster scope
E1215 18:58:18.187421       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:156: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "pods" in API group "" in the namespace "ingress-nginx"
E1215 18:58:18.567289       8 checker.go:41] healthcheck error: Get http+unix://nginx-status/healthz: dial unix /tmp/nginx-status-server.sock: connect: no such file or directory
E1215 18:58:19.194621       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:152: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "endpoints" in API group "" at the cluster scope
E1215 18:58:19.194706       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:156: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "pods" in API group "" in the namespace "ingress-nginx"
E1215 18:58:19.194783       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:155: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "configmaps" in API group "" at the cluster scope
E1215 18:58:19.194931       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:154: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
E1215 18:58:19.195138       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:153: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "services" in API group "" at the cluster scope
E1215 18:58:19.577197       8 checker.go:41] healthcheck error: Get http+unix://nginx-status/healthz: dial unix /tmp/nginx-status-server.sock: connect: no such file or directory
E1215 18:58:20.202482       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:152: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "endpoints" in API group "" at the cluster scope
E1215 18:58:20.202725       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:153: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "services" in API group "" at the cluster scope
E1215 18:58:20.203891       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:155: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "configmaps" in API group "" at the cluster scope
E1215 18:58:20.204279       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:156: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "pods" in API group "" in the namespace "ingress-nginx"
E1215 18:58:20.204493       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:154: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
E1215 18:58:21.213678       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:154: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "secrets" in API group "" at the cluster scope
E1215 18:58:21.213874       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:156: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "pods" in API group "" in the namespace "ingress-nginx"
E1215 18:58:21.214066       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:152: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "endpoints" in API group "" at the cluster scope
E1215 18:58:21.214431       8 reflector.go:126] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:155: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ingre [...]

2021-12-15 20:05 UTC, kollachaitanyakrishna commented
I fixed the issue, by running this command, kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/mandatory.yaml